# Generated by Django 4.0.6 on 2022-07-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
